export const LOCALSTORAGE_PREFIX = "__CREATE_T3_UI__";

export const LOCALSTORAGE_KEYS = {
  REMEMBERED_APP_TYPE: `${LOCALSTORAGE_PREFIX}REMEMBERED_APP_TYPE`,
  APP_TYPE: `${LOCALSTORAGE_PREFIX}APP_TYPE`,
  APP_NAME: `${LOCALSTORAGE_PREFIX}APP_NAME`,
  APP_DIRECTORY: `${LOCALSTORAGE_PREFIX}APP_DIRECTORY`,
};
